app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /{_locale}

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: homepage
        permanent: false
